config/routes.rb
Rails.application.routes.draw do
  resources :employee_infos
  #get 'employee1/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'employee_infos#index'
  get "about", to:'employee_infos#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee_info.rb
class EmployeeInfo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employee1_controller.rb
class Employee1Controller < ApplicationController
  def index
  end
end

app/controllers/employee_infos_controller.rb
class EmployeeInfosController < ApplicationController
  before_action :set_employee_info, only: %i[ show edit update destroy ]
  
  def about
  end
  # GET /employee_infos or /employee_infos.json
  def index
    @employee_infos = EmployeeInfo.all
  end

  # GET /employee_infos/1 or /employee_infos/1.json
  def show
  end

  # GET /employee_infos/new
  def new
    @employee_info = EmployeeInfo.new
  end

  # GET /employee_infos/1/edit
  def edit
  end

  # POST /employee_infos or /employee_infos.json
  def create
    @employee_info = EmployeeInfo.new(employee_info_params)

    respond_to do |format|
      if @employee_info.save
        format.html { redirect_to @employee_info, notice: "Employee info was successfully created." }
        format.json { render :show, status: :created, location: @employee_info }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @employee_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employee_infos/1 or /employee_infos/1.json
  def update
    respond_to do |format|
      if @employee_info.update(employee_info_params)
        format.html { redirect_to @employee_info, notice: "Employee info was successfully updated." }
        format.json { render :show, status: :ok, location: @employee_info }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @employee_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employee_infos/1 or /employee_infos/1.json
  def destroy
    @employee_info.destroy
    respond_to do |format|
      format.html { redirect_to employee_infos_url, notice: "Employee info was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee_info
      @employee_info = EmployeeInfo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def employee_info_params
      params.require(:employee_info).permit(:first_name, :last_name, :email, :phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employee1_helper.rb
module Employee1Helper
end

app/helpers/employee_infos_helper.rb
module EmployeeInfosHelper
end

app/views/employee1/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

 <%= link_to 'Employee App', root_path, class:"navbar-brand" %> 

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      


      
      <li class="nav-item">
         <%= link_to "Add Employee", new_employee_info_path, class:"nav-link" %>
      </li>
      
      <li class="nav-item">
      <%= link_to "Employees list", employee_infos_path, class:"nav-link" %>
      </li>
      
    </ul>

    
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/employee_infos/_form.html.erb
<%= form_with(model: employee_info) do |form| %>
  <% if employee_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee_info.errors.count, "error") %> prohibited this employee_info from being saved:</h2>

      <ul>
        <% employee_info.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.number_field :phone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/employee_infos/about.html.erb
<h1>about page </h1>

app/views/employee_infos/edit.html.erb
<h1>Editing Employee Info</h1>

<%= render 'form', employee_info: @employee_info %>

<%= link_to 'Show', @employee_info %> |
<%= link_to 'Back', employee_infos_path %>

app/views/employee_infos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employee Infos</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employee_infos.each do |employee_info| %>
      <tr>
        <td><%= employee_info.first_name %></td>
        <td><%= employee_info.last_name %></td>
        <td><%= employee_info.email %></td>
        <td><%= employee_info.phone %></td>
        <td><%= link_to 'Show', employee_info %></td>
        <td><%= link_to 'Edit', edit_employee_info_path(employee_info) %></td>
        <td><%= link_to 'Destroy', employee_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee Info', new_employee_info_path %>

app/views/employee_infos/new.html.erb
<h1>New Employee Info</h1>

<%= render 'form', employee_info: @employee_info %>

<%= link_to 'Back', employee_infos_path %>

app/views/employee_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @employee_info.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @employee_info.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @employee_info.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @employee_info.phone %>
</p>

<%= link_to 'Edit', edit_employee_info_path(@employee_info) %> |
<%= link_to 'Back', employee_infos_path %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Employee App</title>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'employee1/header' %>
    <%= yield %>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>